<#
.SYNOPSIS
    Registers the SortView Collector as a Windows Scheduled Task, using
    XML generated by `python -m collector.task_settings` (the single,
    unit-tested source of truth for cadence/overlap/restart/execution-
    limit/principal -- see that module). Never touches C:\SortViewAgent
    or its own Scheduled Task.

.DESCRIPTION
    1. Generates the task XML via the installed venv's own
       `python -m collector.task_settings`.
    2. Registers it via `schtasks /create /xml <file> /tn "SortView
       Collector"`.
    3. Does NOT start the task -- confirm preflight (including the
       SYSTEM-context run, see run-preflight-as-system.ps1) passes first.

    Idempotent: re-running without -Force reports the existing task and
    makes no changes. With -Force, unregisters and re-registers it (task
    run HISTORY is lost; state.json/status.json/logs under -DataRoot are
    never touched by this script either way).

    REMINDER, not bypassed by this script: the collector fails closed
    (exit code 2) until a production Tech Logic parser is wired in during
    a later, separate phase. Registering and even STARTING this task is
    safe and structurally correct -- it will not upload placeholder or
    unparsed data -- but it is not yet doing real production data
    collection. See the printed note at the end of this script and
    docs/collector-v1-admin-guide.md.

.EXAMPLE
    .\register-collector-task.ps1 `
        -InstallRoot "C:\SortView\Collector" `
        -ConfigPath "C:\ProgramData\SortViewCollector\config\collector_config.json"
#>

[CmdletBinding()]
param(
    [string]$InstallRoot = "C:\SortView\Collector",
    [string]$ConfigPath = "C:\ProgramData\SortViewCollector\config\collector_config.json",
    [string]$Principal = "SYSTEM",
    [int]$CadenceMinutes = 15,
    [int]$RestartCount = 3,
    [int]$RestartIntervalMinutes = 5,
    [int]$ExecutionTimeLimitHours = 1,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$TaskName = "SortView Collector"

$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "This script must be run from an elevated (Administrator) PowerShell session."
}

$VenvPython = Join-Path $InstallRoot ".venv\Scripts\python.exe"
if (-not (Test-Path $VenvPython)) {
    throw "Python executable not found at '$VenvPython' -- run install-collector.ps1 first."
}
if (-not (Test-Path $ConfigPath)) {
    Write-Warning "Config file '$ConfigPath' does not exist yet -- the task will fail to start until it does. Continuing to register anyway."
}

$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing -and -not $Force) {
    Write-Host "Task '$TaskName' already exists. Pass -Force to unregister and re-register it. No changes made." -ForegroundColor Yellow
    return
}
if ($existing -and $Force) {
    Write-Host "Removing existing task '$TaskName' before re-registering (per -Force)..."
    $state = (Get-ScheduledTask -TaskName $TaskName).State
    if ($state -eq "Running") { Stop-ScheduledTask -TaskName $TaskName }
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$xmlPath = Join-Path $env:TEMP "sortview-collector-task-$([guid]::NewGuid().ToString('N')).xml"
try {
    & $VenvPython -m collector.task_settings `
        --python-exe $VenvPython `
        --config-path $ConfigPath `
        --working-dir $InstallRoot `
        --output $xmlPath `
        --principal $Principal `
        --cadence-minutes $CadenceMinutes `
        --restart-count $RestartCount `
        --restart-interval-minutes $RestartIntervalMinutes `
        --execution-time-limit-hours $ExecutionTimeLimitHours
    if ($LASTEXITCODE -ne 0) { throw "XML generation failed (exit $LASTEXITCODE)" }

    schtasks /create /xml $xmlPath /tn $TaskName
    if ($LASTEXITCODE -ne 0) { throw "schtasks /create failed (exit $LASTEXITCODE)" }
} finally {
    Remove-Item $xmlPath -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "Registered Scheduled Task '$TaskName'." -ForegroundColor Green
Write-Host "  Working directory: $InstallRoot"
Write-Host "  Config:            $ConfigPath"
Write-Host "  Runs as:           $Principal"
Write-Host "  Cadence:           every $CadenceMinutes minute(s)"
Write-Host "  Overlap policy:    IgnoreNew"
Write-Host "  Restart on failure: $RestartCount attempts, $RestartIntervalMinutes minute(s) apart"
Write-Host "  Execution limit:   $ExecutionTimeLimitHours hour(s)"
Write-Host ""
Write-Host "The task has NOT been started yet. Confirm SORTVIEW_API_TOKEN is set and both" -ForegroundColor Yellow
Write-Host "interactive AND SYSTEM-context preflight pass (run-preflight-as-system.ps1)" -ForegroundColor Yellow
Write-Host "before starting it:" -ForegroundColor Yellow
Write-Host "  Start-ScheduledTask -TaskName '$TaskName'"
Write-Host ""
Write-Host "REMINDER: the collector will FAIL CLOSED (exit code 2, 'parser adapter is not" -ForegroundColor Yellow
Write-Host "yet configured') on every run until the production Tech Logic parser is wired" -ForegroundColor Yellow
Write-Host "in during a later, separate phase. This is expected and safe -- it proves the" -ForegroundColor Yellow
Write-Host "install/scheduling/connectivity layer, not production data collection." -ForegroundColor Yellow
