<#
.SYNOPSIS
    Registers the SortView Collector as a Windows Scheduled Task, using
    XML generated by `python -m collector.task_settings` (the single,
    unit-tested source of truth for cadence/overlap/restart/execution-
    limit/principal -- see that module). Never touches C:\SortViewAgent
    or its own Scheduled Task.

.DESCRIPTION
    1. Generates the task XML via the installed venv's own
       `python -m collector.task_settings`.
    2. Registers it via `schtasks /create /xml <file> /tn "SortView
       Collector"`.
    3. Does NOT start the task -- confirm preflight (including the
       SYSTEM-context run, see run-preflight-as-system.ps1) passes first.

    REGISTERED DISABLED BY DEFAULT (real production finding): a task
    registered with an enabled recurring trigger is armed the instant
    registration completes -- Start-ScheduledTask never being called does
    NOT prevent Task Scheduler from firing it automatically at the next
    StartBoundary/Repetition. Pass -Enabled only if you deliberately want
    the task armed immediately. The normal, safe sequence is: register
    (disabled) -> run both preflight checks -> Enable-ScheduledTask.

    Idempotent: re-running without -Force reports the existing task and
    makes no changes. With -Force, unregisters and re-registers it (task
    run HISTORY is lost; state.json/status.json/logs under -DataRoot are
    never touched by this script either way) -- note that a -Force
    re-registration always applies the CURRENT -Enabled value (default
    disabled), it does not preserve whatever enabled/disabled state the
    task happened to be in before -- so re-running with -Force but
    without re-passing -Enabled will disable a previously-enabled task.
    This is deliberate: every registration is a fresh, explicit decision,
    never an implicit carry-forward.

    REMINDER: the production Tech Logic parser (checkins/rejects/acs) is
    wired in -- registering and starting this task means an ordinary run
    parses and uploads real data for those three sources. The fail-closed
    gate (exit code 2, still not bypassed by this script) remains as a
    safety net for a source name outside those three. See the printed
    note at the end of this script and docs/collector-v1-admin-guide.md.

.EXAMPLE
    .\register-collector-task.ps1 `
        -InstallRoot "C:\SortView\Collector" `
        -ConfigPath "C:\ProgramData\SortViewCollector\config\collector_config.json"
#>

[CmdletBinding()]
param(
    [string]$InstallRoot = "C:\SortView\Collector",
    [string]$ConfigPath = "C:\ProgramData\SortViewCollector\config\collector_config.json",
    [string]$TaskName = "SortView Collector",
    [string]$Principal = "SYSTEM",
    [int]$CadenceMinutes = 15,
    [int]$RestartCount = 3,
    [int]$RestartIntervalMinutes = 5,
    [int]$ExecutionTimeLimitHours = 1,
    # Real production finding: registering a task with an enabled
    # recurring trigger arms it immediately -- Start-ScheduledTask is a
    # separate, on-demand action unrelated to whether the trigger itself
    # is live. Default here is DISABLED (safe); pass -Enabled only when
    # you deliberately want the task armed the instant it's registered.
    [switch]$Enabled,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

if ($TaskName -eq "sortview-scheduler") {
    throw "Refusing to register under the legacy continuous-agent task name 'sortview-scheduler'."
}

$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "This script must be run from an elevated (Administrator) PowerShell session."
}

$VenvPython = Join-Path $InstallRoot ".venv\Scripts\python.exe"
$FrozenExe = Join-Path $InstallRoot "SortViewCollector.exe"
$IsFrozen = (Test-Path $FrozenExe) -and -not (Test-Path $VenvPython)
if (-not (Test-Path $VenvPython) -and -not (Test-Path $FrozenExe)) {
    throw "No installed runtime found at '$InstallRoot' (neither .venv\Scripts\python.exe nor " +
          "SortViewCollector.exe) -- run install.ps1 first."
}
# The executable Task Scheduler will actually launch -- python.exe for a
# source install, SortViewCollector.exe for a frozen one. Also the
# executable this script itself shells out to for XML generation below
# (collector.task_settings, via -m for source or the frozen dispatcher's
# own task-xml subcommand for frozen -- see below).
$RunnerExe = if ($IsFrozen) { $FrozenExe } else { $VenvPython }
if (-not (Test-Path $ConfigPath)) {
    Write-Warning "Config file '$ConfigPath' does not exist yet -- the task will fail to start until it does. Continuing to register anyway."
}

$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing -and -not $Force) {
    Write-Host "Task '$TaskName' already exists. Pass -Force to unregister and re-register it. No changes made." -ForegroundColor Yellow
    return
}
if ($existing -and $Force) {
    Write-Host "Removing existing task '$TaskName' before re-registering (per -Force)..."
    $state = (Get-ScheduledTask -TaskName $TaskName).State
    if ($state -eq "Running") { Stop-ScheduledTask -TaskName $TaskName }
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$xmlPath = Join-Path $env:TEMP "sortview-collector-task-$([guid]::NewGuid().ToString('N')).xml"
try {
    # SOURCE: -m collector.task_settings resolves the `collector` package
    # via the PROCESS'S OWN working directory, not this script's --
    # install.ps1 copies collector\*.py under -InstallRoot, so the child
    # process must be started there, or ModuleNotFoundError results.
    # FROZEN: SortViewCollector.exe's own dispatcher (see
    # collector/freeze/dispatcher.py) exposes the SAME collector.task_settings
    # module as its "task-xml" subcommand -- no Python/venv exists to run
    # "-m collector.task_settings" against in a frozen install, so the
    # frozen exe generates its own task XML instead, via --frozen (which
    # makes the generated Arguments "run --config ..." rather than
    # "-m collector.run --config ..." -- see task_settings.py's own
    # TaskDefinition.frozen field). Push-Location is harmless either way,
    # kept uniform for both branches rather than conditionally skipped.
    Push-Location $InstallRoot
    try {
        $taskSettingsArgs = @(
            "--python-exe", $RunnerExe,
            "--config-path", $ConfigPath,
            "--working-dir", $InstallRoot,
            "--output", $xmlPath,
            "--principal", $Principal,
            "--cadence-minutes", $CadenceMinutes,
            "--restart-count", $RestartCount,
            "--restart-interval-minutes", $RestartIntervalMinutes,
            "--execution-time-limit-hours", $ExecutionTimeLimitHours
        )
        if ($Enabled) { $taskSettingsArgs += "--enabled" }
        if ($IsFrozen) {
            & $RunnerExe @(@("task-xml") + $taskSettingsArgs + @("--frozen"))
        } else {
            & $RunnerExe @(@("-m", "collector.task_settings") + $taskSettingsArgs)
        }
    } finally {
        Pop-Location
    }
    if ($LASTEXITCODE -ne 0) { throw "XML generation failed (exit $LASTEXITCODE)" }

    schtasks /create /xml $xmlPath /tn $TaskName
    if ($LASTEXITCODE -ne 0) { throw "schtasks /create failed (exit $LASTEXITCODE)" }
} finally {
    Remove-Item $xmlPath -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "Registered Scheduled Task '$TaskName'." -ForegroundColor Green
Write-Host "  Working directory: $InstallRoot"
Write-Host "  Config:            $ConfigPath"
Write-Host "  Runs as:           $Principal"
Write-Host "  Cadence:           every $CadenceMinutes minute(s)"
Write-Host "  Overlap policy:    IgnoreNew"
Write-Host "  Restart on failure: $RestartCount attempts, $RestartIntervalMinutes minute(s) apart"
Write-Host "  Execution limit:   $ExecutionTimeLimitHours hour(s)"
Write-Host "  Enabled:           $(if ($Enabled) { 'YES (armed -- will fire at its next trigger)' } else { 'NO (disabled -- safe default)' })"
Write-Host ""

if (-not $Enabled) {
    Write-Host "This task is REGISTERED but DISABLED. It cannot fire on its own schedule in this" -ForegroundColor Yellow
    Write-Host "state, and Windows will not allow Start-ScheduledTask while it remains disabled." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  1. REGISTRATION (done)     -- the task now exists in Task Scheduler, disabled."
    Write-Host "  2. ENABLING (not done)     -- arms the recurring schedule. Do this only after" -ForegroundColor Yellow
    Write-Host "                                confirming BOTH interactive AND SYSTEM-context" -ForegroundColor Yellow
    Write-Host "                                preflight pass (run-preflight-as-system.ps1):"
    Write-Host "       Enable-ScheduledTask -TaskName '$TaskName'"
    Write-Host "  3. MANUAL IMMEDIATE START  -- once enabled, run it immediately on demand:"
    Write-Host "       Start-ScheduledTask -TaskName '$TaskName'"
    Write-Host "     If this is only a controlled test, disable it again after the run:"
    Write-Host "       Disable-ScheduledTask -TaskName '$TaskName'"
    Write-Host "  4. RECURRING EXECUTION     -- while enabled, Task Scheduler runs it every"
    Write-Host "                                $CadenceMinutes minute(s)."
    Write-Host ""
    Write-Host "Real production finding this default addresses: registering a task with an" -ForegroundColor Yellow
    Write-Host "enabled trigger arms it immediately -- Start-ScheduledTask never being called does" -ForegroundColor Yellow
    Write-Host "NOT prevent the recurring schedule from firing on its own. Pass -Enabled to this" -ForegroundColor Yellow
    Write-Host "script only if you deliberately want the task armed the instant it's registered." -ForegroundColor Yellow
} else {
    Write-Host "This task was registered ENABLED (-Enabled was passed) -- its recurring schedule" -ForegroundColor Red
    Write-Host "is ALREADY ARMED and will fire automatically at its next trigger, whether or not" -ForegroundColor Red
    Write-Host "Start-ScheduledTask is ever called. Only use -Enabled after preflight has already" -ForegroundColor Red
    Write-Host "passed -- there is no disable step after the fact except Disable-ScheduledTask." -ForegroundColor Red
}

Write-Host ""
Write-Host "REMINDER: the production Tech Logic parser (checkins/rejects/acs) is wired in --" -ForegroundColor Yellow
Write-Host "once enabled, a run parses and uploads real data for those three sources. The" -ForegroundColor Yellow
Write-Host "fail-closed gate (exit code 2, 'no parser configured') still applies as a safety" -ForegroundColor Yellow
Write-Host "net for any other source name, but is not expected to fire in normal use." -ForegroundColor Yellow
Write-Host ""
Write-Host "Before enabling: if this is a fresh production install (source files already" -ForegroundColor Yellow
Write-Host "contain historical data), seed the starting cursor first, or the first run will" -ForegroundColor Yellow
Write-Host "replay all of it:" -ForegroundColor Yellow
if ($IsFrozen) {
    Write-Host "  `"$RunnerExe`" bootstrap --config `"$ConfigPath`""
} else {
    Write-Host "  $RunnerExe -m collector.bootstrap_state --config `"$ConfigPath`""
}
